version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/bleprint"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/bleprint_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/bleprint_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/bleprint_platform_interface"
    schedule:
      interval: "daily"