name: bleprint
description: BLEPrint is a Flutter plugin to bluetooth thermal printer
version: 0.0.1-dev.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: bleprint_android
      ios:
        default_package: bleprint_ios

dependencies: 
  bleprint_android:
    path: ../bleprint_android
  bleprint_ios:
    path: ../bleprint_ios
  bleprint_platform_interface:
    path: ../bleprint_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
