name: bleprint_platform_interface
description: A common platform interface for the bleprint plugin.
version: 0.0.1-dev.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=3.0.1 <5.0.0"
