name: bleprint_ios
description: iOS implementation of the bleprint plugin
version: 0.0.1-dev.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: bleprint
    platforms:
      ios:
        pluginClass: BleprintPlugin
        dartPluginClass: BleprintIOS

dependencies:
  bleprint_platform_interface:
    path: ../bleprint_platform_interface

  flutter:
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0+1
