name: bleprint_android

on:
  pull_request:
    paths:
      - ".github/workflows/bleprint_android.yaml"
      - "bleprint_android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/bleprint_android.yaml"
      - "bleprint_android/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.0
      working_directory: bleprint_android
